import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { spawn } from 'node:child_process';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root=fileURLToPath(new URL('.',import.meta.url));
const schema=join(root,'recommendation.schema.json');
const port=Number(process.env.PORT||8787);
const facts='已核验事实：Steam《三角洲行动》推荐16GB内存、88GB可用空间；Steam《永劫无间》推荐16GB内存、90GB可用空间并建议SSD。两款游戏同时安装的已知文件空间为178GB，未含系统、更新、启动器和课程文件。';
const send=(res,status,payload)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8'});res.end(JSON.stringify(payload))};
const trace=(step,detail)=>({step,detail,at:new Date().toISOString()});
function readJson(req){return new Promise((ok,bad)=>{let body='',done=false;req.on('data',chunk=>{if(done)return;body+=chunk;if(body.length>16000){done=true;req.destroy();bad(Error('请求内容过长'))}});req.on('end',()=>{if(done)return;try{ok(JSON.parse(body))}catch{bad(Error('请求格式无效'))}});req.on('error',error=>{if(!done)bad(error)})})}
function clean(value,max=600,{empty=false}={}){if(typeof value!=='string'||value.length>max)return null;const output=value.trim();return output?output:(empty?'':null)}
function validate(raw){const budget=Number(raw.budget),config=raw.config||{};if(!Number.isInteger(budget)||budget<2500||budget>30000)throw Error('预算请填写2500到30000之间的整数。');const input={persona:clean(raw.persona,80),region:clean(raw.region,40),needs:clean(raw.needs),constraints:clean(raw.constraints,600,{empty:true}),priority:clean(raw.priority,40)};if(Object.values(input).some(value=>value===null))throw Error('请完整填写需求。');const model=clean(config.model,160);if(!['arkcli','openai'].includes(config.provider)||!model||!/^[A-Za-z0-9._:/-]+$/.test(model))throw Error('模型配置不正确。');let baseUrl='',apiKey='';if(config.provider==='openai'){baseUrl=clean(config.baseUrl,500);apiKey=clean(config.apiKey,800);try{const url=new URL(baseUrl);if(!/^https?:$/.test(url.protocol))throw Error()}catch{throw Error('接口地址必须是有效的 http 或 https URL。')}if(!apiKey)throw Error('OpenAI兼容方式需要API Key。')}return {...input,budget,config:{provider:config.provider,model,baseUrl,apiKey}}}
function prompt(input){return `你是中国大陆DIY主机方案顾问。基于用户需求生成一套最终推荐配置，不是泛泛建议。${facts}\n用户：${input.persona}\n预算：${input.budget}元（仅主机）\n地区：${input.region}\n用途：${input.needs}\n限制：${input.constraints||'无'}\n优先项：${input.priority}\n输出必须是JSON，字段须包含title、fitLabel、summary、totalEstimate、budgetStatus、upgradeAdvice、parts、reasons、purchaseChecks。parts输出7到9项，至少包含CPU、主板、显卡、内存、SSD、电源、散热、机箱；每项含category、recommendation、reason、estimatedPrice。每项给出具体规格或系列，不要写“中端”“主流”。价格只能写估算，不得编造实时价格、库存、店铺或认证；接口、尺寸、电源功率和实时价格必须写入purchaseChecks。`}
function parseModelJson(value){const result=JSON.parse(String(value).replace(/^```json\s*|\s*```$/g,'').trim());if(!Array.isArray(result.parts)||result.parts.length<7||result.parts.length>9||!Array.isArray(result.purchaseChecks)||!Array.isArray(result.reasons))throw Error('模型输出缺少完整配置。');for(const item of result.parts)if(!item||['category','recommendation','reason','estimatedPrice'].some(key=>typeof item[key]!=='string'||item[key].length>800))throw Error('模型部件字段不完整。');return result}
function arkcli(input){return new Promise((ok,bad)=>{const args=['+chat','--model',input.config.model,'--text-format','json_schema','--text-schema',schema,'--text-strict','--max-output-tokens','2200','--thinking','disabled','--format','json',prompt(input)];const child=spawn('arkcli',args,{cwd:root,env:{...process.env,ARKCLI_NO_UPDATE_NOTIFIER:'1',ARKCLI_CALLER_TYPE:'app',ARKCLI_CALLER_NAME:'diy-pc-evidence-card',ARKCLI_SKILL_NAME:'arkcli-chat'}});let out='';const timer=setTimeout(()=>child.kill('SIGTERM'),120000);child.stdout.on('data',chunk=>out+=chunk);child.on('error',error=>{clearTimeout(timer);bad(Error(`无法启动ArkCLI：${error.message}`))});child.on('close',code=>{clearTimeout(timer);if(code!==0)return bad(Error('ArkCLI调用未完成。请确认本机已登录，并稍后重试。'));try{ok(parseModelJson(JSON.parse(out).content))}catch{bad(Error('ArkCLI返回未通过结构校验，请重试。'))}})})}
async function openai(input){try{const response=await fetch(`${input.config.baseUrl.replace(/\/$/,'')}/chat/completions`,{method:'POST',signal:AbortSignal.timeout(90_000),headers:{'content-type':'application/json',authorization:`Bearer ${input.config.apiKey}`},body:JSON.stringify({model:input.config.model,temperature:0.2,messages:[{role:'user',content:prompt(input)}]})});if(!response.ok)throw Error('response');return parseModelJson((await response.json())?.choices?.[0]?.message?.content)}catch(error){if(error.name==='TimeoutError')throw Error('模型接口超时，请稍后重试。');throw Error('模型接口调用失败，请检查接口地址、模型ID和API Key。')}}
async function recommend(input){const started=Date.now();const history=[trace('需求已接收',`预算${input.budget}元｜优先项${input.priority}`),trace('输入校验完成','需求与模型配置已通过本地校验'),trace('调用模型',input.config.provider==='arkcli'?`ArkCLI · ${input.config.model}`:`OpenAI兼容接口 · ${input.config.model}`)];try{const recommendation=input.config.provider==='arkcli'?await arkcli(input):await openai(input);history.push(trace('结构校验完成',`已收到${recommendation.parts.length}项部件与${recommendation.purchaseChecks.length}条购买核验项`),trace('最终配置已生成',`耗时${((Date.now()-started)/1000).toFixed(1)}秒；未记录密钥或完整需求文本`));return {recommendation,trace:history}}catch(error){history.push(trace('运行失败',`阶段：模型调用或结构校验；耗时${((Date.now()-started)/1000).toFixed(1)}秒`));error.trace=history;throw error}}
createServer(async(req,res)=>{try{if(req.method==='POST'&&req.url==='/api/recommend')return send(res,200,await recommend(validate(await readJson(req))));if(req.method!=='GET')return send(res,405,{error:'仅支持GET和POST。'});if(req.url!=='/'&&req.url!=='/index.html')return send(res,404,{error:'未找到资源。'});res.writeHead(200,{'content-type':'text/html; charset=utf-8'});res.end(await readFile(join(root,'index.html'),'utf8'))}catch(error){send(res,400,{error:error.message||'服务错误。',trace:error.trace||[]})}}).listen(port,'127.0.0.1',()=>console.log(`装机证据卡已运行：http://127.0.0.1:${port}`));
