import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { spawn } from 'node:child_process';
import { extname, join, normalize } from 'node:path';
import { fileURLToPath } from 'node:url';

const root=fileURLToPath(new URL('.',import.meta.url));
const schema=join(root,'recommendation.schema.json');
const port=Number(process.env.PORT||8787);
const facts='已核验事实：Steam《三角洲行动》推荐16GB内存、88GB可用空间；Steam《永劫无间》推荐16GB内存、90GB可用空间并建议SSD。两款游戏同时安装的已知文件空间为178GB，未含系统、更新、启动器和课程文件。';
const send=(res,status,payload)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8'});res.end(JSON.stringify(payload))};
function readJson(req){return new Promise((ok,bad)=>{let body='';req.on('data',x=>{body+=x;if(body.length>16000)bad(Error('请求内容过长'))});req.on('end',()=>{try{ok(JSON.parse(body))}catch{bad(Error('请求格式无效'))}});req.on('error',bad)})}
function text(value,max=600){return typeof value==='string'&&value.length<=max?value:''}
function validate(raw){const budget=Number(raw.budget),config=raw.config||{};if(!Number.isFinite(budget)||budget<2500||budget>30000)throw Error('预算请填写2500到30000之间的整数。');for(const key of ['persona','region','needs','constraints','priority'])if(!text(raw[key]))throw Error('请完整填写需求。');if(!['arkcli','openai'].includes(config.provider))throw Error('请选择模型调用方式。');if(!text(config.model,160))throw Error('请填写模型ID。');if(config.provider==='openai'&&(!text(config.baseUrl,500)||!text(config.apiKey,800)))throw Error('OpenAI兼容方式需要接口地址和API Key。');return {...raw,budget,config:{provider:config.provider,model:config.model,baseUrl:text(config.baseUrl,500),apiKey:text(config.apiKey,800)}}}
function prompt(input){return `你是中国大陆DIY主机方案顾问。基于用户需求生成一套最终推荐配置，不是泛泛建议。${facts}\n用户：${input.persona}\n预算：${input.budget}元（仅主机）\n地区：${input.region}\n用途：${input.needs}\n限制：${input.constraints||'无'}\n优先项：${input.priority}\n输出必须是JSON，字段须包含title、fitLabel、summary、totalEstimate、budgetStatus、upgradeAdvice、parts、reasons、purchaseChecks。parts输出7到9项，至少包含CPU、主板、显卡、内存、SSD、电源、散热、机箱；每项含category、recommendation、reason、estimatedPrice。每项给出具体规格或系列，不要写“中端”“主流”。价格只能写估算，不得编造实时价格、库存、店铺或认证；接口、尺寸、电源功率和实时价格必须写入purchaseChecks。`}
function parseModelJson(value){const text=String(value).replace(/^```json\s*|\s*```$/g,'').trim();const result=JSON.parse(text);if(!Array.isArray(result.parts)||result.parts.length<7||!Array.isArray(result.purchaseChecks))throw Error('模型输出缺少完整配置。');return result}
function arkcli(input){return new Promise((ok,bad)=>{const args=['+chat','--model',input.config.model,'--text-format','json_schema','--text-schema',schema,'--text-strict','--max-output-tokens','2200','--thinking','disabled','--format','json',prompt(input)];const child=spawn('arkcli',args,{cwd:root,env:{...process.env,ARKCLI_NO_UPDATE_NOTIFIER:'1',ARKCLI_CALLER_TYPE:'app',ARKCLI_CALLER_NAME:'diy-pc-evidence-card',ARKCLI_SKILL_NAME:'arkcli-chat'}});let out='';const timer=setTimeout(()=>child.kill('SIGTERM'),120000);child.stdout.on('data',x=>out+=x);child.on('error',e=>{clearTimeout(timer);bad(Error(`无法启动ArkCLI：${e.message}`))});child.on('close',code=>{clearTimeout(timer);if(code!==0)return bad(Error('ArkCLI调用未完成。请确认本机已登录，并稍后重试。'));try{ok(parseModelJson(JSON.parse(out).content))}catch{bad(Error('ArkCLI返回未通过结构校验，请重试。'))}})})}
async function openai(input){const base=input.config.baseUrl.replace(/\/$/,'');const response=await fetch(`${base}/chat/completions`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${input.config.apiKey}`},body:JSON.stringify({model:input.config.model,temperature:0.2,response_format:{type:'json_object'},messages:[{role:'user',content:prompt(input)}]})});if(!response.ok)throw Error(`模型接口返回${response.status}，请检查地址、模型ID和API Key。`);const body=await response.json();return parseModelJson(body?.choices?.[0]?.message?.content)}
async function recommend(input){const start=Date.now();const trace=[{step:'需求已接收',detail:`${input.persona}｜${input.budget}元｜${input.priority}`,at:new Date().toISOString()},{step:'输入校验完成',detail:'预算、用途与模型配置已通过本地校验',at:new Date().toISOString()},{step:'调用模型',detail:input.config.provider==='arkcli'?`ArkCLI · ${input.config.model}`:`OpenAI兼容接口 · ${input.config.model}`,at:new Date().toISOString()}];const recommendation=input.config.provider==='arkcli'?await arkcli(input):await openai(input);trace.push({step:'结构校验完成',detail:`已收到${recommendation.parts.length}项部件与${recommendation.purchaseChecks.length}条购买核验项`,at:new Date().toISOString()},{step:'最终配置已生成',detail:`耗时${((Date.now()-start)/1000).toFixed(1)}秒；本次密钥未写入历史记录`,at:new Date().toISOString()});return {recommendation,trace}}
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png'};
createServer(async(req,res)=>{try{if(req.method==='POST'&&req.url==='/api/recommend')return send(res,200,await recommend(validate(await readJson(req))));if(req.method!=='GET')return send(res,405,{error:'仅支持GET和POST。'});const name=req.url==='/'?'index.html':normalize(req.url.split('?')[0]).replace(/^[/\\]+/,'');const file=join(root,name);if(!file.startsWith(root))return send(res,403,{error:'禁止访问。'});const body=await readFile(file);res.writeHead(200,{'content-type':mime[extname(file)]||'application/octet-stream'});res.end(body)}catch(error){send(res,400,{error:error.message||'服务错误。'})}}).listen(port,()=>console.log(`装机证据卡已运行：http://127.0.0.1:${port}`));
